import React, { Component } from 'react';

import PageHeader from '../components/PageHeader';
import Footer from '../components/Footer';

class PrivacyPolicy extends Component {
	render() {
		return (
			<>
				<PageHeader title="Privacy Policy" />
				<section className="general-block bg-grey container-padding4020">
					<div className="container">
						<div className="row">
							<div className="col-12 padding-bottom20">
								<small>Last Edited on – 12/23/2016</small>
							</div>
							<div className="col-12">
								<p>This Privacy Policy describes the way HelpPay Inc., a Delaware (USA) corporation doing business through our mobile phone application, ChangeTransact (CTX), and its affiliates (collectively, "CTX" or "us") obtains, uses, stores, manages and disposes of certain information that you, as a user of our services, provide to us. Please read our privacy policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your Personally Identifiable Information in accordance with our website. It also describes your choices regarding use, access and correction of your personal information.</p>
								<p>CTX first collects information about you and about the person to whom you are sending money (your "Beneficiary") from the data you supply on the CTX application (the "App"). When you provide information to CTX, through the App or otherwise, you are warranting to CTX that all of the information you provide to us about yourself and about your Beneficiary is accurate and complete. CTX is relying on your warranty when CTX provides the Service to you. The information you provide includes Personally Identifiable Information, which is defined as information that can be used, on its own or with other information, to identify you.</p>
								<p>In addition to the information you provide, CTX may have, or may obtain from third parties, information about you or your Beneficiary, some of which may be Personally Identifiable Information. More information about these third parties appears below. CTX uses this information to provide its services to you, and to help protect you, the CTX service, your Beneficiary and the general public from mistakes, fraud, money-laundering and other problems.</p>
								<h5>Collection of Information</h5>
								<p>The initial information we collect from you is the information that you provide to us on the CTX App. This includes information about yourself, such as your full legal name, address, date of birth, telephone number, email address, last four digits of your social security number (if a U.S. Citizen), as well as other information and/or documentation that will allow us to verify your identify. You must also provide us with information about an approved payment source, such as your debit card, and information about your Beneficiary, which may include sensitive personal information such as your Beneficiary's name, address, mobile phone number and/or bank account information. CTX may also collect information from your mobile phone or other device from which you access the CTX App, including your IP (Internet Protocol) address, operating system, device identification information, and other information associated with your access to and use of the App. CTX may also collect information about the websites you have visited prior to accessing the CTX service. CTX may keep and store such information and associate it with your use, in order to help CTX identify you and facilitate your use of our service in the future.</p>
								<p>CTX may verify and confirm all of the information that you provide to us (or that we otherwise collect from your accessing the CTX App) with third parties, including the financial institution that issued the payment card you propose to use, and the telecommunications company or financial institution through which your money is sent to your Beneficiary. CTX may also verify such information with identify verification services, electronic databases, social media companies and credit reporting agencies. CTX may share your information with the banks, telecommunications providers and other financial services firms who facilitate payment to your Beneficiary. From time to time, CTX may require you and/or your Beneficiary to provide us with additional information and/or documentation to confirm your identify and your eligibility to use the CTX service.</p>
								<p>When you access the CTX app, CTX may collect and store information regarding your use of the App and the service. This includes information about the frequency with which you access the App, the time you spend there, the way you move through the site, your transfer history, and details regarding the amount of money you transfer and your Beneficiaries.</p>
								<p>If you contact us for any reason, whether by telephone, email, text or otherwise, CTX may record and store communications that you have with us.</p>
								<h5>Use of Information</h5>
								<p>CTX may maintain and use all of the information and documentation that you provide, as well as information that we derive from your use of the service, and the information that we obtain about you from third parties, in order to provide the CTX service to you, and to enable CTX to comply with laws and regulations, including those intended to prevent fraud, money laundering, and other abuses of the financial system. CTX may use your information to contact you as necessary to confirm or complete a transaction, and to allow our agents, partners and service providers to fulfill their obligations in providing the CTX service to you. CTX may also use your information to improve our service, to troubleshoot problems, to develop new products and services, and to create advertising, marketing and promotional campaigns. (More information about CTX's use of your data for marketing and promotion is below.) Finally, CTX may disclose your information to third parties, including government agencies, when CTX reasonably determines that such disclosure is required by law, such as responses to subpoenas and information requests by law enforcement, financial services regulators or national security authorities.</p>
								<p>CTX will not sell, rent or otherwise disclose your information to third party marketers or others unaffiliated with CTX for the purpose of advertising, promoting or selling other services to you. However, where and to the extent allowed by law, CTX may work with third parties to analyze the information that we gather from you when you visit us on-line, including our website, our Facebook page, and our Facebook advertisements, whether or not you use the CTX service. CTX may use the information we gather there, along with the information we obtain from your use of our service, which may include Personally Identifiable Information, to advertise and promote CTX services to you and to others. For example, CTX provides data to Facebook's Ad Manager account and SDK programs, which provide us with information about the ways customers and other visitors access, view and use the CTX website and application. We use that information to create advertisements and promotions; such advertisements and promotions may appear in your Facebook feed or on other sites owned or operated by Facebook, such as Instagram. We may customize our marketing and promotional messages to you based on your use of our service, the information that you provide to us or which we otherwise obtain about you, and algorithms designed to help us anticipate your potential needs, based on your information and the information of others who use CTX services. CTX believes that such programs provide valuable information and benefits to our current and potential users. However, if you live in the European Community or another jurisdiction where such use of your data for marketing and promotional purposes requires your permission, CTX will not use your data for these purposes unless you "opt in" to such uses.</p>
								<h5>Protection of personal information collected by Wave</h5>
								<p>CTX's leading security experts and practices help ensure that your Personally Identifiable Information is secure. All such information is stored on servers with state-of-the-art data protection technology, and is accessible only to CTX employees who, for business purposes, need to access it. We use 128-bit encryption and encode your debit card information as soon as it is entered in the CTX app, a process that overwrites your details so that they are unreadable by unauthorized parties.</p>
								<p>No method of transmission over the internet, or method of electronic storage, is 100% secure, however. Although CTX uses strong methods to protect the data that you provide to us, and we regularly test our information protection practices and technology, CTX cannot absolutely guarantee its security. We will, however, notify you of any breach or other compromise that affects your data, promptly and in compliance with applicable law.</p>
								<h5>Use of Cookies and other Tracking Devices</h5>
								<p>CTX uses "cookies" and other tracking devices to help us recognize you, remember your preferences and facilitate your future transactions and other interactions with us. We also use such tracking devices to help us understand consumer behavior on our App, in order to help us improve it and make it easier for future use. You may be able to disable your device's use of cookies, but that may slow or prevent your ability to use the CTX service.</p>
								<h5>Your Right to Access and Correct Your Personal Information</h5>
								<p>You have the right to access your personal information stored by CTX, subject to applicable laws and in accordance with relevant data protection regulations and CTX's policies intended to prevent fraud and other abuses of financial services. In order to do so, you can contact us at support@changetransact.com. If the information CTX has maintained about you is wrong, incomplete or otherwise inaccurate, you have the right to require CTX to correct it or correct the information yourself directly in the App.</p>
								<h5>Destruction of Information</h5>
								<p>In general, CTX maintains information about each transaction for five years. After that period, CTX may destroy such information, and it will no longer be available to you or anyone else. However, there may be circumstances in which CTX is required to maintain information for longer periods, if required by law or regulation.</p>
								<h5>Privacy Policy Changes</h5>
								<p>CTX's privacy policy may change in the future. If that happens, the revised version will be posted on our website, https://changetransact.com, and will be sent to current users via the email addresses associated with their CTX App registrations.</p>
								<h5>California Residents:</h5>
								<p>If you have complaints with respect to any aspect of the money transmission activities conducted at this location, you may contact the California Department of Business Oversight at its toll-free telephone number, 1-866-275-2677, by email at consumer.services@dbo.ca.gov, or by mail at the Department of Business Oversight, Consumer Services, 1515 K. Street, Suite 200, Sacramento, CA, 95814.</p>
								<h5>Texas Residents:</h5>
								<p>If you have a complaint, first contact the consumer assistance division of CTX at support@changetransact.com, if you still have an unresolved complaint regarding the company's money transmission or currency exchange activity, please direct your complaint to: Texas Department of Banking, 2601 North Lamar Boulevard, Austin, Texas 78705, 1-877-276-5554 (toll free), www.dob.texas.gov.</p>
								<h5>Arkansas Residents:</h5>
								<p>If you have a complaint, first contact the consumer assistance division of CTX  at support@changetransact.com. If you still have an unresolved complaint regarding the company’s money transmission activity, please direct your complaint to the Arkansas Securities Department, 201 East Markham Street, Little Rock, Arkansas, 72201-1692. The telephone number is 501-324-9260 and the website is: www.securities.arkansas.gov.</p>
							</div>
						</div>
					</div>
				</section>
				<Footer />
			</>
		);
	}
}

export default PrivacyPolicy;
